## Model Configuration
models:
  - namescope: model_0
    type: resnet18
    model_params:
      weight_decay: 0.0001
  - namescope: model_1
    type: resnet18
    model_params:
      weight_decay: 0.0001

# TODO: denoiser configuration?

## Test Configuration
test_frequency: 1
# test_saltpepper: [0.1]
test_models:
  model_0:
    - id: model_0_whitebox
    - id: __generated__
  model_1:
    - id: model_1_whitebox
    - id: __generated__
test_frequency: 1

## Training Configuration
epochs: 30
batch_size: 50
# Learning rate
adjust_lr_acc:
  type: ExpDecay
  start_lr: 0.01
  decay: 0.1
  # decay_every: 25
  boundaries: [1, 16, 32]

# 暂时所有模型的loss参数和lr只有一份配置...之后如果觉得要不一样再说
# Loss
alpha: 0.1
beta: 0
theta: 0.5
temperature: 1
at_mode: attention

## Augmentation Configuration
aug_gaussian: [0.02, 0.1]
aug_saltpepper: [0, 0.2]

## Adversarial Augmentation Configuration
update_per_batch: 1
train_models:
  model_0:
    - id: model_0_whitebox
    - id: __generated__
  model_1:
    - id: model_1_whitebox
    - id: __generated__
train_merge_adv: true
generated_adv:
  - id: inception_on_submit3_l2_03_005_10
    suffix: bin
    path: /home/foxfi/projects/nips2018/generated_advs/l2i_03_005_10

available_attacks:
  - id: model_0_whitebox
    method: pgd
    model: model_0
    attack_params:
      eps: 4.0
      eps_iter: 1.0
      nb_iter: 10
      attack_with_y: false
  - id: model_1_whitebox
    method: pgd
    model: model_1
    attack_params:
      eps: 4.0
      eps_iter: 1.0
      nb_iter: 10
      attack_with_y: false
