## Model
teacher:
  namescope: ""
  type: resnet18
  model_params:
    weight_decay: 0.0001
    test_only: true
model:
  namescope: stu_
  type: resnet18
  model_params:
    weight_decay: 0.0001

## Training
alpha: 0.1
beta: 0
theta: 0.5
temperature: 1
at_mode: attention

test_frequency: 1
epochs: 50
batch_size: 50
adjust_lr_acc:
  type: ExpDecay
  start_lr: 0.01
  decay: 0.1
  decay_every: 15

## Aug
aug_gaussian: [0.02, 0.1]
aug_saltpepper: [0, 0.2]

## Adversarial Aug
update_per_batch: 1
train_models: # iter train
  stu_:
    - id: stu_whitebox
      gid: stu_whitebox
      conds: ["epoch_mod(2, 1)"]
      # - id: _generated
      #   gid: _generated
      #   conds: ["epoch_mod(2, 1)"]
    - id:
      gid: normal
      conds: ["epoch_mod(2, 0)"]

test_models:
  stu_:
    - gid: stu_whitebox
      id: stu_whitebox
    # - id: stu_whitebox
    #   attack_params:
    #     eps: 8.0
    #     eps_iter: 2.0

# generated_adv: # pre-stored adv examples
#   - id: inception_on_submit3_l2_03_005_10
#     suffix: bin
#     path:

available_attacks:
  - id: stu_whitebox
    method: pgd
    model: stu_
    attack_params:
      eps: 4.0
      eps_iter: 1.0
      nb_iter: 10
