## Model Configuration
models:
  - namescope: model_0
    type: resnet18
    model_params:
      weight_decay: 0.0001
  - namescope: model_1
    type: resnet18
    model_params:
      weight_decay: 0.0001

# TODO: denoiser configuration?

## Test Configuration
test_frequency: 1
# test_saltpepper: [0.1]
test_models:
  model_0:
    - id: model_0_whitebox
    - id: __generated__
  model_1:
    - id: model_1_whitebox
    - id: __generated__
test_frequency: 1

## Training Configuration
epochs: 40
batch_size: 50
# Learning rate
adjust_lr_acc:
  type: AccLr
  start_lr: 0.01
  decay: 0.1
  # decay_every: 18
  decay_epoch_threshold: 4
  end_epoch_threshold: 6

distill_use_auged: false
update_per_batch: 1
train_merge_adv: true
train_models:
  model_0:
    - id: model_0_whitebox
      gid: model_0_whitebox
    - id: __generated__
      gid: __generated__
    - id:
      gid: normal
  model_1:
    - id: model_1_whitebox
      gid: model_1_whitebox
    - id: __generated__
      gid: __generated__
    - id:
      gid: normal

# 暂时所有模型的loss参数和lr只有一份配置...之后如果觉得要不一样再说
# Loss
alpha: 0.1
beta: 0
theta: 0.5
temperature: 1
at_mode: attention

## Augmentation Configuration
aug_gaussian: [0.02, 0.1]
aug_saltpepper: [0, 0.2]

generated_adv: # pre-stored adv examples
  - id: inception_nore_l2_16
    suffix: bin
    path: /home/eva_share/foxfi/nips2018/data/inception/nore_inception_pgd_l2_16
  - id: vgg_nore_l2_16
    suffix: bin
    path: /home/eva_share/foxfi/nips2018/data/vgg/nore_vgg_pgd_l2_16
  - id: resnet_nore_l2_16
    suffix: bin
    path: /home/eva_share/foxfi/nips2018/data/resnet/nore_resnet_pgd_l2_16
  - id: inception-res-v2_nore_l2_16
    suffix: bin
    path: /home/eva_share/foxfi/nips2018/data/inception-res-v2/nore_inception-res-v2_pgd_l2_16

## Adversarial Augmentation Configuration
available_attacks:
  - id: model_0_whitebox
    method: pgd
    model: model_0
    attack_params:
      eps: 4.0
      eps_iter: 1.0
      nb_iter: 10
      attack_with_y: false
  - id: model_1_whitebox
    method: pgd
    model: model_1
    attack_params:
      eps: 4.0
      eps_iter: 1.0
      nb_iter: 10
      attack_with_y: false
